// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoD12BZgCesBezJIIMpRDQuRUuTp_pgxk',
    appId: '1:221378458417:web:5787b2ae4940d6119eb610',
    messagingSenderId: '221378458417',
    projectId: 'tennis-app-8be5a',
    authDomain: 'tennis-app-8be5a.firebaseapp.com',
    storageBucket: 'tennis-app-8be5a.firebasestorage.app',
    measurementId: 'G-6KJFBF8T8R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwUyfjIJQT3JbE_BKeESzGmwc0D02_CAM',
    appId: '1:221378458417:android:2bdc250ce3f91e2b9eb610',
    messagingSenderId: '221378458417',
    projectId: 'tennis-app-8be5a',
    storageBucket: 'tennis-app-8be5a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5h3WK8bbSTB_2SWL6STNt0I3Eq7Fcpts',
    appId: '1:221378458417:ios:29cc6d38749d49449eb610',
    messagingSenderId: '221378458417',
    projectId: 'tennis-app-8be5a',
    storageBucket: 'tennis-app-8be5a.firebasestorage.app',
    iosBundleId: 'com.example.projekt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5h3WK8bbSTB_2SWL6STNt0I3Eq7Fcpts',
    appId: '1:221378458417:ios:29cc6d38749d49449eb610',
    messagingSenderId: '221378458417',
    projectId: 'tennis-app-8be5a',
    storageBucket: 'tennis-app-8be5a.firebasestorage.app',
    iosBundleId: 'com.example.projekt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoD12BZgCesBezJIIMpRDQuRUuTp_pgxk',
    appId: '1:221378458417:web:2ec21aeebb2289439eb610',
    messagingSenderId: '221378458417',
    projectId: 'tennis-app-8be5a',
    authDomain: 'tennis-app-8be5a.firebaseapp.com',
    storageBucket: 'tennis-app-8be5a.firebasestorage.app',
    measurementId: 'G-X7CHR2SG4Z',
  );
}
