name: projekt
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter  
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  flutter_bloc: ^9.0.0
  provider: ^6.1.2
  equatable: ^2.0.7
  go_router: ^14.6.2
  animations: ^2.0.11
  hive_flutter: ^1.1.0
  build_runner: ^2.4.13
  encrypt: ^5.0.3
  bloc: ^9.0.0
  shared_preferences: ^2.3.5
  flutter_localizations:
    sdk: flutter
  intl: any

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  firebase_auth_mocks: ^0.14.1
  fake_cloud_firestore: ^3.1.0



flutter:
  uses-material-design: true
  generate: true
