# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      # - uses: dart-lang/setup-dart@v1
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
      - run: flutter --version
        
      
      - name: Install dependencies
        run: flutter pub get
        working-directory: projekt
     
      # Uncomment this step to verify the use of 'dart format' on each commit.
      - name: Verify formatting
        run: dart format --output=none --set-exit-if-changed .

      #Consider passing '--fatal-infos' for slightly stricter analysis.
      - name: Analyze project source
        run: dart analyze
        working-directory: projekt

      # Your project will need to have tests in test/ and a dependency on
      # package:test for this step to succeed. Note that Flutter projects will
      # want to change this to 'flutter test'.
      - name: Run tests
        run: flutter test
        working-directory: projekt

      - name: Build flutter web app
        run: flutter build web
        working-directory: projekt

      - name: Save build output
        uses: actions/upload-artifact@v3
        with:
          name: build-web
          path: projekt/build/web
        
      
  deploy:
    name: Deploy to firebase hosting
    runs-on: ubuntu-latest
    needs: build

    steps:

    - uses: actions/checkout@v4

    - name: Download build
      uses: actions/download-artifact@v3
      with:
        name: build-web


    #- name: Deploy to Firebase Hosting
     # uses: w9jds/firebase-action@master
      #with:
       # args: deploy --only hosting
        #working-directory: projekt
      #env:
       # FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    - name: Deploy to Firebase Hosting
      run: |
        npm install -g firebase-tools
        firebase deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      working-directory: projekt
       

     

      
